// Movies & TV — film grammar, genres, jobs, iconic objects/genres without
// trademark titles (we stay off named IP to keep this license-clean).
export const MOVIES_WORDS: readonly string[] = [
  'ACTOR', 'ACTRESS', 'DIRECTOR', 'PRODUCER', 'EDITOR', 'WRITER', 'SCRIPT',
  'SCENE', 'TAKE', 'CUT', 'WRAP', 'CAST', 'CREW', 'EXTRA', 'STUDIO',
  'PROP', 'SET', 'STAGE', 'COSTUME', 'MAKEUP', 'WARDROBE', 'BACKDROP',
  'CAMERA', 'LENS', 'TRIPOD', 'BOOM', 'DOLLY', 'CRANE', 'STEADICAM',
  'FOCUS', 'ZOOM', 'PAN', 'TILT', 'FRAME', 'SHOT', 'CLOSEUP', 'WIDESHOT',
  'STUNT', 'EFFECTS', 'GREENSCREEN', 'MOTIONCAPTURE', 'STORYBOARD',
  'TRAILER', 'POSTER', 'PREMIERE', 'OPENING', 'CREDITS', 'SOUNDTRACK',
  'SCORE', 'THEME', 'FOLEY', 'DUBBING', 'SUBTITLE', 'SCREEN', 'PROJECTOR',
  'THEATER', 'MULTIPLEX', 'POPCORN', 'CONCESSION', 'TICKET', 'BOX',
  'OSCAR', 'EMMY', 'GOLDEN', 'AWARD', 'NOMINATION', 'BLOCKBUSTER',
  'SEQUEL', 'PREQUEL', 'REBOOT', 'REMAKE', 'CAMEO', 'SPINOFF',
  'GENRE', 'DRAMA', 'COMEDY', 'HORROR', 'THRILLER', 'ROMANCE', 'WESTERN',
  'MUSICAL', 'NOIR', 'SCIFI', 'FANTASY', 'ANIMATION', 'DOCUMENTARY',
  'HERO', 'VILLAIN', 'SIDEKICK', 'MENTOR', 'NEMESIS', 'PROTAGONIST',
  'COWBOY', 'NINJA', 'PIRATE', 'ZOMBIE', 'VAMPIRE', 'WEREWOLF', 'MUMMY',
  'DETECTIVE', 'SPY', 'AGENT', 'ASSASSIN', 'HITMAN', 'SHERIFF',
  'CLIFFHANGER', 'PLOT', 'TWIST', 'FLASHBACK', 'MONTAGE', 'SOLILOQUY',
  'CRITIC', 'REVIEW', 'RATING', 'BUDGET', 'GROSS', 'OPENING',
  'CHANNEL', 'NETWORK', 'EPISODE', 'SEASON', 'FINALE', 'PILOT', 'SERIES',
  'SITCOM', 'RERUN', 'SYNDICATION', 'BINGE', 'STREAM', 'NETFLIX',
];
